# Generated by Django 2.2.16 on 2022-08-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20220731_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название произведения'),
        ),
    ]
